config/routes.rb
Rails.application.routes.draw do
  root 'microposts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to:'sessions#destroy'
  resources :users
  resources :microposts
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :user_id, presence: true
  validates :micropost_id, presence: true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :iine_users, through: :likes, source: :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 50 }
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader

    #選択したmicropost上にlikeを付与する。user_idは受け取ったcurrent_userのidを適用する
    def likeadd(user)
      likes.create(user_id: user.id)
    end

     #選択したmicropost上のlikeをcurrent_userのidで検索し、likeを解除する
    def likedel(user)
      likes.find_by(user_id: user.id).destroy
    end

    #current_userがいいねしているか確認する
    def like?(user)
      iine_users.include?(user)
    end

    def self.search(search)
      if search
        where("stars=?",search)#入力された値と同じ星の数の投稿を返す
      else
        all 
      end
    end

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  before_save { email.downcase! }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  def logged_in_user
      redirect_to login_path unless logged_in?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
before_action :logged_in_user

  def create
    @micropost = Micropost.find(params[:micropost_id])
    #該当したmicropostがcurrent_userでlikeされていなければ実行
      unless @micropost.like?(current_user)
        #likeを付与する
        @micropost.likeadd(current_user)
        @micropost.reload
        respond_to do |format|
          format.html { redirect_to request.referrer || root_url }
          format.js
        end
      end
  end

  def destroy
    #選択したlikeのmicropostを検索する
    @micropost = Like.find(params[:id]).micropost
    #該当したmicropostがcurrent_userでlikeされていれば実行
    if @micropost.like?(current_user)
      #likeを解除する
      @micropost.likedel(current_user)
      @micropost.reload
      respond_to do |format|
        format.html { redirect_to request.referrer || root_url }
        format.js
      end
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

before_action :logged_in_user, only:[:new,:create,:destroy]

  def new
    #current_userに紐づいたmicropostオブジェクトを返す
    @micropost = current_user.microposts.build
  end

  def create
    #postされた情報でcurrent_userに紐づいたmicropostを作成する
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "投稿完了しました"
      redirect_to microposts_path
    end
  end

  def index
    #micropost.model.rb => def serch
    @microposts = Micropost.paginate(page: params[:page]).search(params[:search])
    #最新のmicropost４件を取得する
    @micropost = Micropost.find_by_sql("select * from microposts order by created_at DESC limit 4")

  end

  def destroy
    Micropost.find(params[:id]).destroy
    flash[:success] = "投稿を削除しました"
    redirect_to request.referrer || root_url
  end

  private
  def micropost_params
    params.require(:micropost).permit(:content,:picture,:stars,:serch)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to microposts_path
    else
      render :new
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only:[:index,:edit,:destroy]
  before_action :correct_user, only:[:edit,:update,:destroy]

  #get users#new
  def new
    @user = User.new
    #form_for(@user)
  end

  #post users#new
  def create
    @user = User.new(user_params)
    if @user.save
      #success
      log_in @user
      flash[:info] = "アカウントが作成されました"
      redirect_to root_path
    else
      #failure
      render　:new
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts
  end

  #get users
  def index
    @users = User.all
    #from_for @users
  end

  #get users#edit
  def edit
    @user = User.find(params[:id])
  end

  #post users#edit
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "アカウント情報が更新されました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  #post users#destroy
  def destroy

    User.find(params[:id]).destroy
    flash[:success] = "アカウントが削除されました"
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(
        :name, :email, :password,
        :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to users_path unless @user == @current_user
    end

    def admin_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if(user_id = session[:user_id])
      @current_user ||= User.find_by(id:session[:user_id])
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  def logged_in?
    !current_user.nil?
  end
  def currentuser_correct?
    @user.id == session[:user_id]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">© 2018. Created by heeeta</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">ReviewM</a>
  <ul class="nav justify-content-end">
    <% if logged_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">MENU<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "MYPAGE", user_path(@current_user.id) %></li>
          <li><%= link_to "TIMELINE", root_path %></li>
          <li><%= link_to "POST", new_micropost_path%></li>　
          <li><%= link_to "LOGOUT", logout_path, method: :delete %></li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "LOGIN", login_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RevieM</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="row">
    <div class="col-md-4 col-md-offset-4">
    <%= yield %>
    </div>
    </div>
    <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if micropost.like?(current_user) %>
  <%= form_with(model: micropost, method: :delete, remote:true) do |f| %>
    <%= button_tag(class: "btn btn-default btn-xs") do %>
      <%= content_tag :span, micropost.likes.count, class: "fa fa-heart red" %>
    <% end %>
  <% end %>
<% else %>
  <%= form_with(model: micropost, url: likes_path, remote: true) do |f| %>
    <div><%= hidden_field_tag :micropost_id, micropost.id %></div>
    <%= button_tag(class: "btn btn-default btn-xs") do %>
      <%= content_tag :span, micropost.likes.count, class: "fa fa-heart-o" %>
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$("#like-of-<%= @micropost.id %>").html("<%= escape_javascript(render "likes/like", micropost: @micropost) %>");

app/views/likes/destroy.js.erb
$("#like-of-<%= @micropost.id %>").html("<%= escape_javascript(render "likes/like", micropost: @micropost) %>");

app/views/microposts/index.html.erb
<div class = "serchbox">
  <p>検索</p>
  <%= form_tag(microposts_path, method: :get) do %>
    <%= number_field_tag :search %>
    <%= submit_tag 'Search', :stars => nil %>
      <% end %>
         </div>
      <div class="slideSet">
        <% @micropost.each_with_index do |micropostp,i|%>
          <div class = "slide#{i+1}">
            <% image_tag micropostp.picture.url if micropostp.picture? %>
          </div>
        <% end %>
      </div>
      <%= will_paginate %>
        <% @microposts.each do |micropost| %>
        <div class="panel panel-default">
        <div class="panel-body">
          <ul class="media-list">
          <li class="media">
          <a class = "media-left media-bottom">
            <%= image_tag micropost.picture.url if micropost.picture? %>
          </a>
          <div class = "media-body ">
            <h3>
              <span class = "glyphicon glyphicon-user gray"></span>
              <%= link_to micropost.user.name, micropost.user %>
            </h3>
            <% (micropost.stars.to_i).times do |s| %>
              <span class = "fa fa-star red"></span>
            <% end %>
            <% (5-micropost.stars.to_i).times do |s| %>
              <span class = "fa fa-star-o"></span>
            <% end %>
            <%= micropost.content %>
            <a id="like-of-<%= micropost.id %>">
              <%= render 'likes/like', micropost: micropost %>
            </a>
          </div>
        </li>
        </ul>
        </div>
        </div>
         <% end %>
        </div>
      </div>
    </div>

app/views/microposts/new.html.erb
<%= form_with (model: @micropost) do |f| %>
    <form class="form-horizontal">
    <div class="form-group">
      <div class="input-group">
      <span class="input-group-addon">投稿内容</span>
      <%= f.text_area :content, placeholder: "テキスト入力欄", class: 'form-control' %>
    </div>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'btn-prima' %>
    <%= f.select :stars, {'★1' => 1 , '★2' => 2, '★3' => 3, '★4' => 4, '★5' => 5}%>
  </div>
    <%= f.submit "Post", class: "btn btn-primary btn-block" %>
<% end %>
<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/users/edit.html.erb
<h1>UserEdit</h1>
<%= form_with(model: @user) do |f|%>
<form class="form-horizontal">
  <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit "SaveChange", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/users/index.html.erb
<h1>投稿者たち</h1>
<ul class="users">
  <% @users.each do |user| %>
   <%= link_to user.name, user %>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>SignUp</h1>
<%= form_with(model: @user) do |f|%>
  <form class="form-horizontal">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
      <%= f.submit "AccountCreate", class: "btn btn-primary btn-block" %>
  </form>
<% end %>

app/views/users/show.html.erb
<p><span class = "glyphicon glyphicon-user gray"></span>
  <%= @user.name %>
  <% if currentuser_correct? %>
    <%= link_to "edit?", edit_user_path %>
    <%= link_to "delete?", @user , :method => :delete %>
  <% end %>
  <% if @user.microposts.any? %>
    (<%= @user.microposts.count %>POSTS)
  </p>
    <% @microposts.each do |micropost| %>
    <div class="well pull-left">
      <ul class="media-list ">
        <li><%= image_tag micropost.picture.url if micropost.picture? %>
        <li><%= micropost.content %>
        <li><% (micropost.stars.to_i).times do |i|%>
          <span class = "fa fa-star red"></span>
          <% end %>
          <% (5-micropost.stars.to_i).times do |i|%>
          <span class = "fa fa-star-o"></span>
          <% end %>
          <%= content_tag :li, micropost.likes.count, class: "fa fa-heart red" %>
          <% if currentuser_correct? %>
        <li><%= link_to "delete?", micropost , method: :delete, data: { confirm: "You sure?" } %>
        </ul>
      </div>
      <% end %>
    <% end %>
   <% end %>
 </div>
 </div>
 </aside>
</div>